development:
username: 'acreilly3@gmail.com'
password: 'Testing123!'
endpoint: 'development.avalara.net'
account: '1100113096'
servicepathtax: '/1.0/tax/'
servicepathaddress: '/1.0/address/'
license_key: '1D13EDA2DCCC7E4A'
iseligible: 'true'

test:
username: 'acreilly3@gmail.com'
password: 'Testing123!'
endpoint: 'development.avalara.net'

production:
username: 'acreilly3@gmail.com'
password: 'Testing123!'
endpoint: 'development.avalara.net'